name: 'Copy files action'
description: 'Copy Version folders from a to b'
author: 'Gaodeyi'
inputs:
  repository-name:
    description: 'The name of the repository'
  destination-root:
    required: true
    description: 'The root of the destination to copy to'
  object-type:
    required: true
    description: 'The type the object is. Allowed input: Object, Objects, Peripheral, Peripherals'
    default: 'options'
outputs:
  new-path:
    description: 'The new output path, if successfully copied'
runs:
  using: 'node16'
  main: 'dist/index.js'
